import { Hono } from "hono";
import { ANALYSIS_TYPE } from "../../constants.ts";
import { now } from "../../db/helpers.ts";
import { db } from "../../db/index.ts";
import { generatePRDMarkdown } from "../../helpers/format.ts";
import { saveToGitHub } from "../../helpers/github.ts";
import { getOwnedSession, isResponse } from "../../helpers/session-ownership.ts";
import type { AppEnv } from "../../types.ts";

export const githubSaveRoutes = new Hono<AppEnv>();

// POST /sessions/:id/github-save — Save PRD & spec to GitHub repo
githubSaveRoutes.post("/sessions/:id/github-save", async (c) => {
  try {
    // 1. 認証チェック
    const user = c.get("user");
    if (!user) {
      return c.json({ error: "ログインが必要です" }, 401);
    }

    // 2. GitHub トークンの存在チェック
    const userRow = await db.selectFrom("users").select(["github_token"]).where("id", "=", user.id).executeTakeFirst();
    if (!userRow?.github_token) {
      return c.json({ error: "GitHub 連携が必要です。GitHub でログインしてください。" }, 400);
    }

    // 3. セッション所有権チェック
    const result = await getOwnedSession(c);
    if (isResponse(result)) return result;
    const session = result;
    const id = session.id;

    // 4. 分析結果の存在チェック
    const prdRow = await db
      .selectFrom("analysis_results")
      .select("data")
      .where("session_id", "=", id)
      .where("type", "=", ANALYSIS_TYPE.PRD)
      .executeTakeFirst();
    const specRow = await db
      .selectFrom("analysis_results")
      .select("data")
      .where("session_id", "=", id)
      .where("type", "=", ANALYSIS_TYPE.SPEC)
      .executeTakeFirst();

    if (!prdRow || !specRow) {
      return c.json({ error: "PRD と実装仕様を先に生成してください" }, 400);
    }

    const prdData = JSON.parse(prdRow.data);
    const specData = JSON.parse(specRow.data);

    // PRD Markdown を生成
    const prd = prdData.prd || prdData;
    const prdMarkdown = generatePRDMarkdown(prd, session.theme);

    // README を生成
    const readme = `# ${session.theme}

> Generated by [DeepForm](https://deepform.exe.xyz)

## Files

- **PRD.md** — Product Requirements Document
- **spec.json** — Implementation specification for coding agents

## Usage

Copy \`spec.json\` and paste it into your coding agent (Claude Code, Cursor, exe.dev, etc.) to start implementation.
`;

    // 5. GitHub に保存
    const saveResult = await saveToGitHub({
      token: userRow.github_token,
      sessionId: id,
      theme: session.theme,
      files: [
        { path: "PRD.md", content: prdMarkdown },
        { path: "spec.json", content: JSON.stringify(specData, null, 2) },
        { path: "README.md", content: readme },
      ],
      existingRepoUrl: session.github_repo_url,
    });

    // 6. github_repo_url を保存
    await db
      .updateTable("sessions")
      .set({ github_repo_url: saveResult.repoUrl, updated_at: now() })
      .where("id", "=", id)
      .execute();

    return c.json(saveResult);
  } catch (e) {
    console.error("GitHub save error:", e);
    const message = e instanceof Error ? e.message : "Internal Server Error";
    // トークン期限切れの場合
    if (message.includes("401")) {
      return c.json({ error: "GitHub トークンが期限切れです。再度ログインしてください。" }, 401);
    }
    return c.json({ error: message }, 500);
  }
});
